name: On pull request

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

jobs:
  # TODO: verify readme generation

  rustfmt:
    name: Style & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: rustfmt
        run: make format

      - name: Rigorous lint via Clippy
        run: make lint

  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: make build

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Test Go example
        run: |
          make build-go-example
          cd examples/golang
          go run main_ubuntu.go

  build-and-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install protoc
        run: brew install protobuf

      - name: Build
        run: make build

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Test Go example
        run: |
          make build-go-example
          cd examples/golang
          go run main_macos.go

  # TODO: fix windows build if possible -- unable to compile protosocket-rpc because
  # of "no method named `set_reuse_port` found for struct `Socket`"
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install protoc
  #       run: choco install protoc

  #     - name: Build
  #       run: cargo build --verbose