name: On push to main

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}

jobs:
  rustfmt:
    name: Style & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: rustfmt
        run: make format

      - name: Rigorous lint via Clippy
        run: make lint

  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: make build

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Test Go example
        run: |
          make build-go-example
          cd examples/golang
          go run main_ubuntu.go

  build-and-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install protoc
        run: brew install protobuf

      - name: Build
        run: make build

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Test Go example
        run: |
          make build-go-example
          cd examples/golang
          go run main_macos.go

  # TODO: readme generation

  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    # needs: [generate_readme]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

  publish-macos-assets:
    runs-on: ubuntu-latest
    needs: [release-please]
    strategy:
      matrix:
        architecture:
          - { target: x86_64-apple-darwin, use-cross: false }
          - { target: aarch64-apple-darwin, use-cross: true }
    env:
      MACOSX_DEPLOYMENT_TARGET: 15.0
      RUSTFLAGS: --print=native-static-libs -C strip=symbols
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Print version number
        run: |
          echo "Version number: ${{ needs.release-please.outputs.version }}"

      - name: Install protoc
        run: brew install protobuf

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.architecture.target }}
          override: true
          profile: minimal # minimal component installation (ie, no documentation)

      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.architecture.use-cross }}
          command: build
          args: --locked --release --target=${{ matrix.architecture.target }}
  
      - name: Inspect Build
        run: |
          ls target
          ls target/release
        shell: bash

      - name: Publish the C static library and header file
        run: |
          VERSION=${{ needs.release-please.outputs.version }}
          ARCHIVE_FILE="momento-protosocket-ffi-$VERSION.${{ matrix.architecture.target }}.tar.gz"
          HEADER_FILE="./target/momento-protosocket-ffi.h"
          LIBRARY_FILE="./target/${{ matrix.architecture.target }}/release/libmomento_protosocket_ffi.a"
          tar -zcvf $ARCHIVE_FILE $HEADER_FILE $LIBRARY_FILE
          AUTH="Authorization: token ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}"
          LATEST_RELEASE=$(curl -sH "$AUTH" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/v${VERSION})
          RELEASE_ID=$(echo $LATEST_RELEASE | jq -r .id)
          GH_ASSET="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${ARCHIVE_FILE}"
          echo $GH_ASSET
          curl --data-binary @$ARCHIVE_FILE -H "$AUTH" -H "Content-Type: application/octet-stream" $GH_ASSET
        shell: bash

  publish-linux-assets:
    runs-on: ubuntu-latest
    needs: [release-please]
    strategy:
      matrix:
        architecture:
          - { target: aarch64-unknown-linux-gnu, use-cross: true }
          - { target: x86_64-unknown-linux-gnu, use-cross: true }
    env:
      RUSTFLAGS: --print=native-static-libs -C strip=symbols
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Print version number
        run: |
          echo "Version number: ${{ needs.release-please.outputs.version }}"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.architecture.target }}
          override: true
          profile: minimal # minimal component installation (ie, no documentation)
  
      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.architecture.use-cross }}
          command: build
          args: --locked --release --target=${{ matrix.architecture.target }}
  
      - name: Inspect Build
        run: |
          ls target
          ls target/release
        shell: bash

      - name: Publish the C static library and header file
        run: |
          VERSION=${{ needs.release-please.outputs.version }}
          ARCHIVE_FILE="momento-protosocket-ffi-$VERSION.${{ matrix.architecture.target }}.tar.gz"
          HEADER_FILE="./target/momento-protosocket-ffi.h"
          LIBRARY_FILE="./target/${{ matrix.architecture.target }}/release/libmomento_protosocket_ffi.a"
          tar -zcvf $ARCHIVE_FILE $HEADER_FILE $LIBRARY_FILE
          AUTH="Authorization: token ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}"
          LATEST_RELEASE=$(curl -sH "$AUTH" https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/v${VERSION})
          RELEASE_ID=$(echo $LATEST_RELEASE | jq -r .id)
          GH_ASSET="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${ARCHIVE_FILE}"
          echo $GH_ASSET
          curl --data-binary @$ARCHIVE_FILE -H "$AUTH" -H "Content-Type: application/octet-stream" $GH_ASSET
        shell: bash
      